-- ============================================================================
-- ESQUEMA COMPLETO - Proyecto Logística H.M.
-- Proyecto Supabase: yaqbccvlenouqmtqrlrq
-- Base de datos    : db.yaqbccvlenouqmtqrlrq.supabase.co (us-east-2)
-- Fecha de extracción: 2026-08-27
-- Método: Management API de Supabase (v1/projects/{ref}/database/query)
-- con SQL real sobre catálogos del sistema (pg_catalog / information_schema).
-- Este archivo refleja el esquema VIVO, incluidos nombres exactos de
-- constraints, índices, funciones, triggers, políticas RLS y comentarios.
-- ============================================================================
-- CONTENIDO
--   1. Extensiones
--   2. Tipos ENUM
--   3. Tablas (8) y restricciones (PK / UNIQUE / FK)
--   4. Índices
--   5. Funciones (definiciones exactas pg_get_functiondef)
--   6. Triggers activos y event trigger ensure_rls
--   7. Row Level Security (RLS): enable + políticas de todas las tablas
--   8. Comentarios de columnas
-- ============================================================================

-- Nota: gen_random_uuid() está disponible en PostgreSQL 13+ sin extensión.
-- En Supabase la extensión pgcrypto suele estar instalada igualmente:

-- CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ============================================================================
-- 1. TIPOS ENUM
-- ============================================================================

CREATE TYPE public.disponibilidad AS ENUM (
    'reservado',
    'liberado'
);

CREATE TYPE public.estado_solicitud AS ENUM (
    'pendiente',
    'priorizada',
    'asignada',
    'calendarizada',
    'en_transito',
    'entregada',
    'cancelada',
    'finalizada',
    'pendiente_aprobacion',
    'aprobada',
    'rechazada'
);

CREATE TYPE public.rol_usuario AS ENUM (
    'ejecutivo',
    'jefe_local',
    'logistica',
    'administrador'
);

CREATE TYPE public.tipo_notificacion AS ENUM (
    'NUEVA_SOLICITUD',
    'SOLICITUD_PRIORIZADA',
    'SOLICITUD_ASIGNADA',
    'SOLICITUD_CALENDARIZADA',
    'SOLICITUD_EN_TRANSITO',
    'SOLICITUD_ENTREGADA',
    'SOLICITUD_FINALIZADA',
    'SOLICITUD_CANCELADA',
    'VEHICULO_RESERVADO',
    'VEHICULO_LIBERADO',
    'NUEVA_OBSERVACION'
);

CREATE TYPE public.tipo_solicitud AS ENUM (
    'evento',
    'venta'
);

-- ============================================================================
-- 2. TABLAS (columnas, tipos, nullabilidad, defaults e identidad)
--    ******** Las restricciones (PK/UNIQUE/FK) se emiten en la sección 3
--    ******** para conservar los nombres EXACTOS del servidor.
-- ============================================================================

CREATE TABLE public.usuario (
    id uuid NOT NULL,
    nombre varchar(100) NOT NULL,
    apellido varchar(100) NOT NULL,
    email varchar(255) NOT NULL,
    rol public.rol_usuario NOT NULL,
    created_at timestamp DEFAULT now(),
    updated_at timestamp DEFAULT now(),
    activo boolean DEFAULT true,
    requiere_cambio_clave boolean DEFAULT false,
    intentos_fallidos integer DEFAULT 0,
    bloqueado_hasta timestamptz,
    sucursal_id bigint
);

CREATE TABLE public.sucursal (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    usuario_id uuid,
    nombre varchar,
    direccion varchar,
    slots bigint,
    slots_ocupados bigint DEFAULT '0'::bigint
);

CREATE TABLE public.solicitud (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    ejecutivo_id uuid,
    jefe_local_id uuid,
    logistica_id uuid,
    estado public.estado_solicitud NOT NULL DEFAULT 'pendiente'::estado_solicitud,
    fecha_creacion timestamp DEFAULT now(),
    fecha_actualizacion timestamp DEFAULT now(),
    tipo_solicitud public.tipo_solicitud NOT NULL DEFAULT 'venta'::tipo_solicitud,
    sucursal bigint,
    fecha_tentativa_despacho timestamptz,
    fecha_despacho timestamptz,
    motivo_cancelacion text,
    posicion_prioridad bigint,
    fecha_limite timestamptz,
    direccion_evento text,
    titulo_evento text,
    sucursal_destino bigint
);

CREATE TABLE public.vehiculo (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    chasis varchar(17) NOT NULL,
    patente varchar(10) NOT NULL,
    marca varchar(100) NOT NULL,
    modelo varchar(100) NOT NULL,
    anio integer NOT NULL,
    color varchar(50),
    created_at timestamp DEFAULT now(),
    updated_at timestamp DEFAULT now(),
    vendido boolean DEFAULT false
);

CREATE TABLE public.solicitud_vehiculo (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    solicitud_id uuid NOT NULL,
    vehiculo_id uuid NOT NULL,
    created_at timestamp DEFAULT now(),
    disponibilidad public.disponibilidad NOT NULL DEFAULT 'reservado'::disponibilidad
);

CREATE TABLE public.auditoria (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    usuario_id uuid NOT NULL,
    entidad varchar NOT NULL,
    entidad_id uuid NOT NULL,
    accion varchar NOT NULL,
    valor_anterior jsonb,
    valor_nuevo jsonb,
    created_at timestamp DEFAULT now()
);

CREATE TABLE public.observacion (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    solicitud_id uuid NOT NULL,
    usuario_id uuid NOT NULL,
    observacion text NOT NULL,
    created_at timestamp DEFAULT now(),
    updated_at timestamp DEFAULT now()
);

CREATE TABLE public.notificacion (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    usuario_id uuid NOT NULL,
    emisor_id uuid NOT NULL,
    tipo public.tipo_notificacion NOT NULL,
    titulo varchar(100) NOT NULL,
    mensaje text NOT NULL,
    leida boolean NOT NULL DEFAULT false,
    entidad varchar(50) NOT NULL,
    entidad_id uuid NOT NULL,
    ruta text,
    created_at timestamp DEFAULT now()
);

-- ============================================================================
-- 3. RESTRICCIONES (nombres exactos del servidor)
-- ============================================================================

ALTER TABLE public.auditoria ADD CONSTRAINT auditoria_pkey PRIMARY KEY (id);
ALTER TABLE public.auditoria ADD CONSTRAINT auditoria_usuario_fk FOREIGN KEY (usuario_id) REFERENCES usuario(id);
ALTER TABLE public.notificacion ADD CONSTRAINT notificacion_pkey PRIMARY KEY (id);
ALTER TABLE public.notificacion ADD CONSTRAINT notificacion_usuario_fk FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON DELETE CASCADE;
ALTER TABLE public.notificacion ADD CONSTRAINT notificacion_emisor_fk FOREIGN KEY (emisor_id) REFERENCES usuario(id) ON DELETE CASCADE;
ALTER TABLE public.observacion ADD CONSTRAINT observacion_pkey PRIMARY KEY (id);
ALTER TABLE public.observacion ADD CONSTRAINT solicitud_observacion_solicitud_fk FOREIGN KEY (solicitud_id) REFERENCES solicitud(id) ON DELETE CASCADE;
ALTER TABLE public.observacion ADD CONSTRAINT solicitud_observacion_usuario_fk FOREIGN KEY (usuario_id) REFERENCES usuario(id);
ALTER TABLE public.solicitud ADD CONSTRAINT solicitud_pkey PRIMARY KEY (id);
ALTER TABLE public.solicitud ADD CONSTRAINT solicitud_ejecutivo_id_fkey FOREIGN KEY (ejecutivo_id) REFERENCES usuario(id);
ALTER TABLE public.solicitud ADD CONSTRAINT solicitud_jefe_local_id_fkey FOREIGN KEY (jefe_local_id) REFERENCES usuario(id);
ALTER TABLE public.solicitud ADD CONSTRAINT solicitud_logistica_id_fkey FOREIGN KEY (logistica_id) REFERENCES usuario(id);
ALTER TABLE public.solicitud ADD CONSTRAINT solicitud_sucursal_fkey FOREIGN KEY (sucursal) REFERENCES sucursal(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public.solicitud ADD CONSTRAINT solicitud_sucursal_destino_fkey FOREIGN KEY (sucursal_destino) REFERENCES sucursal(id);
ALTER TABLE public.solicitud ADD CONSTRAINT solicitud_sucursal_posicion_prioridad_key UNIQUE (sucursal, posicion_prioridad);
ALTER TABLE public.solicitud_vehiculo ADD CONSTRAINT solicitud_vehiculo_pkey PRIMARY KEY (id);
ALTER TABLE public.solicitud_vehiculo ADD CONSTRAINT solicitud_vehiculo_solicitud_fk FOREIGN KEY (solicitud_id) REFERENCES solicitud(id) ON DELETE CASCADE;
ALTER TABLE public.solicitud_vehiculo ADD CONSTRAINT solicitud_vehiculo_vehiculo_fk FOREIGN KEY (vehiculo_id) REFERENCES vehiculo(id);
ALTER TABLE public.solicitud_vehiculo ADD CONSTRAINT solicitud_vehiculo_unique UNIQUE (solicitud_id, vehiculo_id);
ALTER TABLE public.sucursal ADD CONSTRAINT sucursal_pkey PRIMARY KEY (id);
ALTER TABLE public.sucursal ADD CONSTRAINT sucursal_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public.usuario ADD CONSTRAINT usuario_pkey PRIMARY KEY (id);
ALTER TABLE public.usuario ADD CONSTRAINT usuario_email_key UNIQUE (email);
ALTER TABLE public.usuario ADD CONSTRAINT usuario_auth_fk FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.usuario ADD CONSTRAINT usuario_sucursal_fkey FOREIGN KEY (sucursal_id) REFERENCES sucursal(id);
ALTER TABLE public.vehiculo ADD CONSTRAINT vehiculo_pkey PRIMARY KEY (id);
ALTER TABLE public.vehiculo ADD CONSTRAINT vehiculo_chasis_key UNIQUE (chasis);
ALTER TABLE public.vehiculo ADD CONSTRAINT vehiculo_patente_key UNIQUE (patente);

-- ============================================================================
-- 4. ÍNDICES (además de los generados por PK/UNIQUE)
-- ============================================================================

CREATE INDEX idx_solicitud_sucursal_destino ON public.solicitud USING btree (sucursal_destino);
CREATE INDEX idx_usuario_activo ON public.usuario USING btree (activo);
CREATE INDEX idx_usuario_email ON public.usuario USING btree (email);
CREATE INDEX idx_usuario_rol ON public.usuario USING btree (rol);

-- ============================================================================
-- 5. FUNCIONES (definiciones exactas pg_get_functiondef)
-- ============================================================================

CREATE OR REPLACE FUNCTION public.auditoria_disponibilidad()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN

    -- Caso 1: Se asigna un vehículo nuevo a una solicitud
    IF TG_OP = 'INSERT' THEN

        INSERT INTO public.auditoria (
            usuario_id,
            entidad,
            entidad_id,
            accion,
            valor_anterior,
            valor_nuevo
        )
        VALUES (
            auth.uid(),
            'solicitud_vehiculo',
            NEW.id,
            'ASIGNACION_VEHICULO',
            NULL,
            jsonb_build_object(
                'solicitud_id', NEW.solicitud_id,
                'vehiculo_id', NEW.vehiculo_id,
                'disponibilidad', NEW.disponibilidad
            )
        );

        RETURN NEW;

    END IF;


    -- Caso 2: Cambia la disponibilidad del vehículo dentro de la solicitud
    IF TG_OP = 'UPDATE' 
       AND OLD.disponibilidad IS DISTINCT FROM NEW.disponibilidad THEN

        INSERT INTO public.auditoria (
            usuario_id,
            entidad,
            entidad_id,
            accion,
            valor_anterior,
            valor_nuevo
        )
        VALUES (
            auth.uid(),
            'solicitud_vehiculo',
            NEW.id,
            'CAMBIO_DISPONIBILIDAD_VEHICULO',
            jsonb_build_object(
                'disponibilidad', OLD.disponibilidad
            ),
            jsonb_build_object(
                'disponibilidad', NEW.disponibilidad
            )
        );

    END IF;


    RETURN NEW;

END;
$function$

CREATE OR REPLACE FUNCTION public.cambio_estado_auditoria()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN

    -- Solo registrar si el estado realmente cambió
    IF OLD.estado IS DISTINCT FROM NEW.estado THEN

        INSERT INTO public.auditoria (
            usuario_id,
            entidad,
            entidad_id,
            accion,
            valor_anterior,
            valor_nuevo
        )
        VALUES (
            auth.uid(),
            'solicitud',
            NEW.id,
            'CAMBIO_ESTADO',
            jsonb_build_object(
                'estado', OLD.estado
            ),
            jsonb_build_object(
                'estado', NEW.estado
            )
        );

    END IF;

    RETURN NEW;

END;
$function$

CREATE OR REPLACE FUNCTION public.disponibilidad()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$BEGIN

    IF NEW.estado = 'cancelada'
       AND OLD.estado IS DISTINCT FROM NEW.estado THEN

        UPDATE public.solicitud_vehiculo
        SET disponibilidad = 'liberado'
        WHERE solicitud_id = NEW.id
          AND disponibilidad = 'reservado';

    END IF;

    RETURN NEW;

END;$function$

CREATE OR REPLACE FUNCTION public.handle_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    NEW.updated_at = timezone('utc'::text, now());
    RETURN NEW;
END;
$function$

CREATE OR REPLACE FUNCTION public.handle_new_auth_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
    v_nombre TEXT;
    v_apellido TEXT;
    v_rol TEXT;
BEGIN
    v_nombre := COALESCE(NEW.raw_user_meta_data->>'nombre', 'Usuario');
    v_apellido := COALESCE(NEW.raw_user_meta_data->>'apellido', '');
    v_rol := COALESCE(NEW.raw_user_meta_data->>'rol', 'ejecutivo');

    -- Si es el email del administrador principal, asegurar rol administrador
    IF LOWER(NEW.email) = 'maic.hernandez.dev@gmail.com' THEN
        v_rol := 'administrador';
    END IF;

    INSERT INTO public.usuario (
        id,
        email,
        nombre,
        apellido,
        rol,
        activo,
        requiere_cambio_clave
    )
    VALUES (
        NEW.id,
        NEW.email,
        v_nombre,
        v_apellido,
        v_rol,
        true,
        COALESCE((NEW.raw_user_meta_data->>'requiere_cambio_clave')::boolean, false)
    )
    ON CONFLICT (id) DO UPDATE SET
        email = EXCLUDED.email,
        nombre = CASE WHEN public.usuario.nombre = 'Usuario' THEN EXCLUDED.nombre ELSE public.usuario.nombre END,
        apellido = CASE WHEN public.usuario.apellido = '' THEN EXCLUDED.apellido ELSE public.usuario.apellido END,
        rol = CASE WHEN LOWER(EXCLUDED.email) = 'maic.hernandez.dev@gmail.com' THEN 'administrador' ELSE public.usuario.rol END,
        activo = true;

    RETURN NEW;
EXCEPTION WHEN OTHERS THEN
    -- Evitar que errores secundarios bloqueen auth.users
    RETURN NEW;
END;
$function$

CREATE OR REPLACE FUNCTION public.validate_solicitud_tipo()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  IF NEW.tipo_solicitud = 'venta' THEN
    IF NEW.sucursal_destino IS NULL THEN
      RAISE EXCEPTION 'Una solicitud de tipo venta debe tener sucursal destino.';
    END IF;
  END IF;

  IF NEW.tipo_solicitud = 'evento' THEN
    IF NEW.direccion_evento IS NULL OR TRIM(NEW.direccion_evento) = '' THEN
      RAISE EXCEPTION 'Una solicitud de tipo evento debe tener direccion del evento.';
    END IF;
    IF NEW.titulo_evento IS NULL OR TRIM(NEW.titulo_evento) = '' THEN
      RAISE EXCEPTION 'Una solicitud de tipo evento debe tener titulo del evento.';
    END IF;
  END IF;

  RETURN NEW;
END;
$function$

CREATE OR REPLACE FUNCTION public.es_administrador()
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
    v_rol TEXT;
    v_activo BOOLEAN;
BEGIN
    SELECT rol, activo INTO v_rol, v_activo
    FROM public.usuario
    WHERE id = auth.uid();

    RETURN (v_rol = 'administrador' AND COALESCE(v_activo, true) = true);
END;
$function$

CREATE OR REPLACE FUNCTION public.tiene_rol(VARIADIC roles text[])
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
    SELECT EXISTS (
        SELECT 1 FROM public.usuario
        WHERE id = auth.uid()
          AND COALESCE(activo, true) = true
          AND rol::text = ANY(roles)
    );
$function$

CREATE OR REPLACE FUNCTION public.usuario_activo()
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
    SELECT EXISTS (
        SELECT 1 FROM public.usuario
        WHERE id = auth.uid()
          AND COALESCE(activo, true) = true
    );
$function$

CREATE OR REPLACE FUNCTION public.notificar_observacion()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
    v_ejecutivo_id uuid;
    v_jefe_local_id uuid;
    v_logistica_id uuid;
BEGIN

    -- Obtener los participantes de la solicitud
    SELECT
        ejecutivo_id,
        jefe_local_id,
        logistica_id
    INTO
        v_ejecutivo_id,
        v_jefe_local_id,
        v_logistica_id
    FROM public.solicitud
    WHERE id = NEW.solicitud_id;

    ------------------------------------------------------------------
    -- Notificar al Ejecutivo
    ------------------------------------------------------------------
    IF v_ejecutivo_id IS NOT NULL
       AND v_ejecutivo_id <> NEW.usuario_id THEN

        INSERT INTO public.notificacion (
            usuario_id,
            emisor_id,
            tipo,
            titulo,
            mensaje,
            entidad,
            entidad_id,
            ruta
        )
        VALUES (
            v_ejecutivo_id,
            NEW.usuario_id,
            'NUEVA_OBSERVACION',
            'Nueva observación',
            'Se agregó una nueva observación en la solicitud.',
            'observacion',
            NEW.id,
            '/solicitudes/' || NEW.solicitud_id
        );

    END IF;

    ------------------------------------------------------------------
    -- Notificar al Jefe Local
    ------------------------------------------------------------------
    IF v_jefe_local_id IS NOT NULL
       AND v_jefe_local_id <> NEW.usuario_id THEN

        INSERT INTO public.notificacion (
            usuario_id,
            emisor_id,
            tipo,
            titulo,
            mensaje,
            entidad,
            entidad_id,
            ruta
        )
        VALUES (
            v_jefe_local_id,
            NEW.usuario_id,
            'NUEVA_OBSERVACION',
            'Nueva observación',
            'Se agregó una nueva observación en la solicitud.',
            'observacion',
            NEW.id,
            '/solicitudes/' || NEW.solicitud_id
        );

    END IF;

    ------------------------------------------------------------------
    -- Notificar a Logística
    ------------------------------------------------------------------
    IF v_logistica_id IS NOT NULL
       AND v_logistica_id <> NEW.usuario_id THEN

        INSERT INTO public.notificacion (
            usuario_id,
            emisor_id,
            tipo,
            titulo,
            mensaje,
            entidad,
            entidad_id,
            ruta
        )
        VALUES (
            v_logistica_id,
            NEW.usuario_id,
            'NUEVA_OBSERVACION',
            'Nueva observación',
            'Se agregó una nueva observación en la solicitud.',
            'observacion',
            NEW.id,
            '/solicitudes/' || NEW.solicitud_id
        );

    END IF;

    RETURN NEW;

END;
$function$

CREATE OR REPLACE FUNCTION public.notificar_solicitud()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN

    ------------------------------------------------------------------
    -- NUEVA SOLICITUD
    ------------------------------------------------------------------
    IF TG_OP = 'INSERT' THEN

        INSERT INTO public.notificacion (
            usuario_id,
            emisor_id,
            tipo,
            titulo,
            mensaje,
            entidad,
            entidad_id,
            ruta
        )
        VALUES (
            NEW.jefe_local_id,
            NEW.ejecutivo_id,
            'NUEVA_SOLICITUD',
            'Nueva solicitud',
            'Se creó una nueva solicitud pendiente de priorización.',
            'solicitud',
            NEW.id,
            '/solicitudes/' || NEW.id
        );

        RETURN NEW;

    END IF;

    ------------------------------------------------------------------
    -- SOLO SI CAMBIÓ EL ESTADO
    ------------------------------------------------------------------

    IF OLD.estado IS DISTINCT FROM NEW.estado THEN

        CASE NEW.estado

            WHEN 'priorizada' THEN

                INSERT INTO public.notificacion (
                    usuario_id,
                    emisor_id,
                    tipo,
                    titulo,
                    mensaje,
                    entidad,
                    entidad_id,
                    ruta
                )
                VALUES (
                    NEW.ejecutivo_id,
                    auth.uid(),
                    'SOLICITUD_PRIORIZADA',
                    'Solicitud priorizada',
                    'Tu solicitud fue priorizada.',
                    'solicitud',
                    NEW.id,
                    '/solicitudes/' || NEW.id
                );

            WHEN 'asignada' THEN

                INSERT INTO public.notificacion (
                    usuario_id,
                    emisor_id,
                    tipo,
                    titulo,
                    mensaje,
                    entidad,
                    entidad_id,
                    ruta
                )
                VALUES (
                    NEW.logistica_id,
                    auth.uid(),
                    'SOLICITUD_ASIGNADA',
                    'Nueva solicitud asignada',
                    'Se te asignó una nueva solicitud.',
                    'solicitud',
                    NEW.id,
                    '/solicitudes/' || NEW.id
                );

            WHEN 'calendarizada' THEN

                INSERT INTO public.notificacion (
                    usuario_id,
                    emisor_id,
                    tipo,
                    titulo,
                    mensaje,
                    entidad,
                    entidad_id,
                    ruta
                )
                VALUES (
                    NEW.ejecutivo_id,
                    auth.uid(),
                    'SOLICITUD_CALENDARIZADA',
                    'Solicitud calendarizada',
                    'La entrega fue calendarizada.',
                    'solicitud',
                    NEW.id,
                    '/solicitudes/' || NEW.id
                );

            WHEN 'en_transito' THEN

                INSERT INTO public.notificacion (
                    usuario_id,
                    emisor_id,
                    tipo,
                    titulo,
                    mensaje,
                    entidad,
                    entidad_id,
                    ruta
                )
                VALUES (
                    NEW.ejecutivo_id,
                    auth.uid(),
                    'SOLICITUD_EN_TRANSITO',
                    'Vehículo en tránsito',
                    'El vehículo ya se encuentra en tránsito.',
                    'solicitud',
                    NEW.id,
                    '/solicitudes/' || NEW.id
                );

            WHEN 'entregada' THEN

                INSERT INTO public.notificacion (
                    usuario_id,
                    emisor_id,
                    tipo,
                    titulo,
                    mensaje,
                    entidad,
                    entidad_id,
                    ruta
                )
                VALUES (
                    NEW.ejecutivo_id,
                    auth.uid(),
                    'SOLICITUD_ENTREGADA',
                    'Vehículo entregado',
                    'El vehículo fue entregado.',
                    'solicitud',
                    NEW.id,
                    '/solicitudes/' || NEW.id
                );

            WHEN 'finalizada' THEN

                INSERT INTO public.notificacion (
                    usuario_id,
                    emisor_id,
                    tipo,
                    titulo,
                    mensaje,
                    entidad,
                    entidad_id,
                    ruta
                )
                VALUES (
                    NEW.ejecutivo_id,
                    auth.uid(),
                    'SOLICITUD_FINALIZADA',
                    'Solicitud finalizada',
                    'La solicitud fue finalizada.',
                    'solicitud',
                    NEW.id,
                    '/solicitudes/' || NEW.id
                );

            WHEN 'cancelada' THEN

                INSERT INTO public.notificacion (
                    usuario_id,
                    emisor_id,
                    tipo,
                    titulo,
                    mensaje,
                    entidad,
                    entidad_id,
                    ruta
                )
                VALUES (
                    NEW.ejecutivo_id,
                    auth.uid(),
                    'SOLICITUD_CANCELADA',
                    'Solicitud cancelada',
                    'La solicitud fue cancelada.',
                    'solicitud',
                    NEW.id,
                    '/solicitudes/' || NEW.id
                );

                IF NEW.logistica_id IS NOT NULL THEN

                    INSERT INTO public.notificacion (
                        usuario_id,
                        emisor_id,
                        tipo,
                        titulo,
                        mensaje,
                        entidad,
                        entidad_id,
                        ruta
                    )
                    VALUES (
                        NEW.logistica_id,
                        auth.uid(),
                        'SOLICITUD_CANCELADA',
                        'Solicitud cancelada',
                        'La solicitud fue cancelada.',
                        'solicitud',
                        NEW.id,
                        '/solicitudes/' || NEW.id
                    );

                END IF;

        END CASE;

    END IF;

    RETURN NEW;

END;
$function$

CREATE OR REPLACE FUNCTION public.notificar_solicitud_vehiculo()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
    v_ejecutivo_id uuid;
BEGIN

    -- Obtener el ejecutivo asociado a la solicitud
    SELECT ejecutivo_id
    INTO v_ejecutivo_id
    FROM public.solicitud
    WHERE id = NEW.solicitud_id;

    ------------------------------------------------------------------
    -- VEHÍCULO RESERVADO
    ------------------------------------------------------------------
    IF TG_OP = 'INSERT' THEN

        INSERT INTO public.notificacion (
            usuario_id,
            emisor_id,
            tipo,
            titulo,
            mensaje,
            entidad,
            entidad_id,
            ruta
        )
        VALUES (
            v_ejecutivo_id,
            auth.uid(),
            'VEHICULO_RESERVADO',
            'Vehículo reservado',
            'Se reservó un vehículo para tu solicitud.',
            'solicitud_vehiculo',
            NEW.id,
            '/solicitudes/' || NEW.solicitud_id
        );

        RETURN NEW;

    END IF;

    ------------------------------------------------------------------
    -- VEHÍCULO LIBERADO
    ------------------------------------------------------------------
    IF OLD.disponibilidad IS DISTINCT FROM NEW.disponibilidad THEN

        IF NEW.disponibilidad = 'liberado' THEN

            INSERT INTO public.notificacion (
                usuario_id,
                emisor_id,
                tipo,
                titulo,
                mensaje,
                entidad,
                entidad_id,
                ruta
            )
            VALUES (
                v_ejecutivo_id,
                auth.uid(),
                'VEHICULO_LIBERADO',
                'Vehículo liberado',
                'El vehículo asociado a tu solicitud fue liberado.',
                'solicitud_vehiculo',
                NEW.id,
                '/solicitudes/' || NEW.solicitud_id
            );

        END IF;

    END IF;

    RETURN NEW;

END;
$function$

CREATE OR REPLACE FUNCTION public.rls_auto_enable()
 RETURNS event_trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'pg_catalog'
AS $function$
DECLARE
  cmd record;
BEGIN
  FOR cmd IN
    SELECT *
    FROM pg_event_trigger_ddl_commands()
    WHERE command_tag IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
      AND object_type IN ('table','partitioned table')
  LOOP
     IF cmd.schema_name IS NOT NULL AND cmd.schema_name IN ('public') AND cmd.schema_name NOT IN ('pg_catalog','information_schema') AND cmd.schema_name NOT LIKE 'pg_toast%' AND cmd.schema_name NOT LIKE 'pg_temp%' THEN
      BEGIN
        EXECUTE format('alter table if exists %s enable row level security', cmd.object_identity);
        RAISE LOG 'rls_auto_enable: enabled RLS on %', cmd.object_identity;
      EXCEPTION
        WHEN OTHERS THEN
          RAISE LOG 'rls_auto_enable: failed to enable RLS on %', cmd.object_identity;
      END;
     ELSE
        RAISE LOG 'rls_auto_enable: skip % (either system schema or not in enforced list: %.)', cmd.object_identity, cmd.schema_name;
     END IF;
  END LOOP;
END;
$function$

-- ============================================================================
-- 6. TRIGGERS ACTIVOS EN EL SERVIDOR
-- ============================================================================

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION handle_new_auth_user();

DROP TRIGGER IF EXISTS tr_validate_solicitud_tipo ON public.solicitud;
CREATE TRIGGER tr_validate_solicitud_tipo BEFORE INSERT OR UPDATE ON public.solicitud FOR EACH ROW EXECUTE FUNCTION validate_solicitud_tipo();

DROP TRIGGER IF EXISTS trigger_disponibilidad ON public.solicitud;
CREATE TRIGGER trigger_disponibilidad AFTER UPDATE OF estado ON public.solicitud FOR EACH ROW EXECUTE FUNCTION disponibilidad();

DROP TRIGGER IF EXISTS tr_usuario_updated_at ON public.usuario;
CREATE TRIGGER tr_usuario_updated_at BEFORE UPDATE ON public.usuario FOR EACH ROW EXECUTE FUNCTION handle_updated_at();

-- Event trigger ensure_rls: habilita RLS automáticamente en tablas creadas en public.
-- CREATE EVENT TRIGGER ensure_rls ON ddl_command_end EXECUTE FUNCTION public.rls_auto_enable();

-- ============================================================================
-- 7. ROW LEVEL SECURITY
-- ============================================================================

ALTER TABLE public.auditoria ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notificacion ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.observacion ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.solicitud ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.solicitud_vehiculo ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sucursal ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.usuario ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vehiculo ENABLE ROW LEVEL SECURITY;

-- ---------- Políticas (expresiones EXACTAS de pg_policies) ----------

CREATE POLICY "auditoria_select_admin" ON public.auditoria FOR SELECT TO authenticated USING (tiene_rol(VARIADIC ARRAY['administrador'::text]));
CREATE POLICY "notificacion_delete_destinatario" ON public.notificacion FOR DELETE TO authenticated USING ((usuario_activo() AND (usuario_id = auth.uid())));
CREATE POLICY "notificacion_select_destinatario" ON public.notificacion FOR SELECT TO authenticated USING ((usuario_activo() AND (usuario_id = auth.uid())));
CREATE POLICY "notificacion_update_destinatario" ON public.notificacion FOR UPDATE TO authenticated USING ((usuario_activo() AND (usuario_id = auth.uid()))) WITH CHECK ((usuario_activo() AND (usuario_id = auth.uid())));
CREATE POLICY "observacion_delete_autor_o_admin" ON public.observacion FOR DELETE TO authenticated USING ((usuario_activo() AND ((usuario_id = auth.uid()) OR tiene_rol(VARIADIC ARRAY['administrador'::text]))));
CREATE POLICY "observacion_insert_participantes" ON public.observacion FOR INSERT TO authenticated WITH CHECK ((usuario_activo() AND (usuario_id = auth.uid()) AND (EXISTS (SELECT 1 FROM solicitud s WHERE ((s.id = observacion.solicitud_id) AND ((s.ejecutivo_id = auth.uid()) OR (s.jefe_local_id = auth.uid()) OR (s.logistica_id = auth.uid())))))));
CREATE POLICY "observacion_select_participantes" ON public.observacion FOR SELECT TO authenticated USING ((usuario_activo() AND (tiene_rol(VARIADIC ARRAY['administrador'::text]) OR (EXISTS (SELECT 1 FROM solicitud s WHERE ((s.id = observacion.solicitud_id) AND ((s.ejecutivo_id = auth.uid()) OR (s.jefe_local_id = auth.uid()) OR (s.logistica_id = auth.uid()))))))));
CREATE POLICY "observacion_update_autor_o_admin" ON public.observacion FOR UPDATE TO authenticated USING ((usuario_activo() AND ((usuario_id = auth.uid()) OR tiene_rol(VARIADIC ARRAY['administrador'::text])))) WITH CHECK ((usuario_activo() AND ((usuario_id = auth.uid()) OR tiene_rol(VARIADIC ARRAY['administrador'::text]))));
CREATE POLICY "solicitud_delete_admin" ON public.solicitud FOR DELETE TO authenticated USING (tiene_rol(VARIADIC ARRAY['administrador'::text]));
CREATE POLICY "solicitud_insert_ejecutivo" ON public.solicitud FOR INSERT TO authenticated WITH CHECK ((tiene_rol(VARIADIC ARRAY['administrador'::text, 'ejecutivo'::text]) AND (ejecutivo_id = auth.uid())));
CREATE POLICY "solicitud_select_participantes" ON public.solicitud FOR SELECT TO authenticated USING ((usuario_activo() AND (tiene_rol(VARIADIC ARRAY['administrador'::text]) OR (ejecutivo_id = auth.uid()) OR (jefe_local_id = auth.uid()) OR (logistica_id = auth.uid()) OR (tiene_rol(VARIADIC ARRAY['jefe_local'::text]) AND (estado = ANY (ARRAY['pendiente'::estado_solicitud, 'priorizada'::estado_solicitud])) AND (sucursal = (SELECT u.sucursal_id FROM usuario u WHERE (u.id = auth.uid())))))));
CREATE POLICY "solicitud_update_participantes" ON public.solicitud FOR UPDATE TO authenticated USING ((usuario_activo() AND (tiene_rol(VARIADIC ARRAY['administrador'::text]) OR (ejecutivo_id = auth.uid()) OR (jefe_local_id = auth.uid()) OR (logistica_id = auth.uid()) OR (tiene_rol(VARIADIC ARRAY['jefe_local'::text]) AND (sucursal = (SELECT u.sucursal_id FROM usuario u WHERE (u.id = auth.uid()))))))) WITH CHECK (usuario_activo());
CREATE POLICY "sv_delete_admin" ON public.solicitud_vehiculo FOR DELETE TO authenticated USING (tiene_rol(VARIADIC ARRAY['administrador'::text]));
CREATE POLICY "sv_insert_logistica" ON public.solicitud_vehiculo FOR INSERT TO authenticated WITH CHECK (tiene_rol(VARIADIC ARRAY['administrador'::text, 'logistica'::text]));
CREATE POLICY "sv_select_participantes" ON public.solicitud_vehiculo FOR SELECT TO authenticated USING ((usuario_activo() AND (tiene_rol(VARIADIC ARRAY['administrador'::text]) OR (EXISTS (SELECT 1 FROM solicitud s WHERE ((s.id = solicitud_vehiculo.solicitud_id) AND ((s.ejecutivo_id = auth.uid()) OR (s.jefe_local_id = auth.uid()) OR (s.logistica_id = auth.uid()))))))));
CREATE POLICY "sv_update_logistica" ON public.solicitud_vehiculo FOR UPDATE TO authenticated USING (tiene_rol(VARIADIC ARRAY['administrador'::text, 'logistica'::text])) WITH CHECK (tiene_rol(VARIADIC ARRAY['administrador'::text, 'logistica'::text]));
CREATE POLICY "sucursal_admin_total" ON public.sucursal FOR ALL TO authenticated USING (tiene_rol(VARIADIC ARRAY['administrador'::text])) WITH CHECK (tiene_rol(VARIADIC ARRAY['administrador'::text]));
CREATE POLICY "sucursal_select_autenticados" ON public.sucursal FOR SELECT TO authenticated USING (usuario_activo());
CREATE POLICY "Administradores pueden actualizar usuarios" ON public.usuario FOR UPDATE TO public USING ((es_administrador() OR (auth.uid() = id)));
CREATE POLICY "Administradores pueden eliminar usuarios" ON public.usuario FOR DELETE TO public USING (es_administrador());
CREATE POLICY "Administradores pueden insertar usuarios" ON public.usuario FOR INSERT TO public WITH CHECK ((es_administrador() OR (auth.uid() = id)));
CREATE POLICY "Administradores pueden ver todos los usuarios" ON public.usuario FOR SELECT TO public USING (es_administrador());
CREATE POLICY "Usuarios pueden ver su propio perfil" ON public.usuario FOR SELECT TO public USING ((auth.uid() = id));
CREATE POLICY "vehiculo_delete_admin" ON public.vehiculo FOR DELETE TO authenticated USING (tiene_rol(VARIADIC ARRAY['administrador'::text]));
CREATE POLICY "vehiculo_insert_gestores" ON public.vehiculo FOR INSERT TO authenticated WITH CHECK (tiene_rol(VARIADIC ARRAY['administrador'::text, 'jefe_local'::text, 'logistica'::text]));
CREATE POLICY "vehiculo_select_autenticados" ON public.vehiculo FOR SELECT TO authenticated USING (usuario_activo());
CREATE POLICY "vehiculo_update_gestores" ON public.vehiculo FOR UPDATE TO authenticated USING (tiene_rol(VARIADIC ARRAY['administrador'::text, 'jefe_local'::text, 'logistica'::text])) WITH CHECK (tiene_rol(VARIADIC ARRAY['administrador'::text, 'jefe_local'::text, 'logistica'::text]));

-- ============================================================================
-- 8. COMENTARIOS DE COLUMNAS (objetos en el servidor)
-- ============================================================================

COMMENT ON COLUMN public.solicitud.sucursal IS 'Sucursal desde la que nace la solcitud';
COMMENT ON COLUMN public.solicitud.fecha_tentativa_despacho IS 'Fecha tentativa en la que el despacho estaria programado';
COMMENT ON COLUMN public.solicitud.fecha_despacho IS 'Fecha real de salida del vehiculo desde logistica';
COMMENT ON COLUMN public.solicitud.motivo_cancelacion IS 'Motivo de la cancelacion de una solicitud';
COMMENT ON COLUMN public.solicitud.posicion_prioridad IS 'Numero que indica que prioridad tiene una solicitud';
COMMENT ON COLUMN public.solicitud_vehiculo.disponibilidad IS 'Indica si un vehiculo que ya tuvo una solicitud puede estar disponible para otra soliciutd si el estado es reservado entonces no si es liberado entonces si';